name = "JLDPC"
uuid = "34ce51a5-b66c-4777-8aeb-ae820e817496"
authors = ["Gabriel Chua Yu Han <tmscyh@nus.edu.sg> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
